### ISSUE TITLE
Russian language

### ISSUE THREAD

**Issue by KirpichKrasniy** [Levatius/pokemon-legends#5]
hello, can you insert my translation of the game into Russian if I send it to you?
at the moment I have just started translating the main maps, but I think that I will quickly finish the translation of maps and game mechanics, and then I will translate the rules and other things

**Comment by KirpichKrasniy** [comment]
![полный перевод деки1а](https://user-images.githubusercontent.com/109726461/208934834-7331193c-bcb4-43a4-9ab7-dd54cd73f2e8.png)
![полный перевод деки1б](https://user-images.githubusercontent.com/109726461/208934865-31602068-ab66-4b41-bfdb-57471afb9dba.png)

**Comment by KirpichKrasniy** [comment]
So far, everything has been done very sloppily ...

or can you create cards based on my translation using a card generator, I just don’t understand it at all?

**Comment by KirpichKrasniy** [comment]
[все движения по алфавиту.txt](https://github.com/Levatius/pokemon-legends/files/10278755/default.txt)
I myself just took all the movements from the Excel spreadsheet and translated it into a separate txt file, and from there I already port it to the picture in Photoshop

**Comment by Levatius** [comment]
You can post it on the workshop as a separate mod if you want to! Much like how this one has been done: https://steamcommunity.com/sharedfiles/filedetails/?id=2880340481

**Comment by KirpichKrasniy** [comment]
with your permission, I will post my work on steam when I finish it. I will post links to your work. you made a really cool game. this is the best pokemon game in the last 10 years. <3
